services:
  - type: web
    name: odoo18-app
    env: docker
    plan: free
    branch: main
    region: oregon
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: DB_HOST
        fromService:
          type: pserv
          name: odoo18-db
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        value: odoo
      - key: DB_PASSWORD
        value: your_secure_password
      - key: DB_NAME
        value: odoo
  - type: pserv
    name: odoo18-db
    env: postgres
    plan: free
    region: oregon
    databases:
      - name: odoo
