[options]
addons_path = addons,vunda_addons
admin_passwd = admin
db_host = postgresql://sandrovunda:4D25Y9m7UBvAasz2Le8XOW6h6PG1gBPE@dpg-d27khjmuk2gs73ea2qe0-a/vundexbd_cipl
db_name = false
db_port = 5432
db_user = sandrovunda
db_password = 4D25Y9m7UBvAasz2Le8XOW6h6PG1gBPE
logfile = /odoo/log/odoo.log
log_level = info
