[options]
addons_path = addons,odoo/addons
admin_passwd = admin
db_host = ${DB_HOST}
db_port = ${DB_PORT}
db_user = ${DB_USER}
db_password = ${DB_PASSWORD}
logfile = /odoo/log/odoo.log
log_level = info
