[options]
addons_path = addons,odoo/addons
admin_passwd = admin
db_host = dpg-d27khjmuk2gs73ea2qe0-a
db_port = 5432
db_user = sandrovunda
db_password = 4D25Y9m7UBvAasz2Le8XOW6h6PG1gBPE
logfile = /odoo/log/odoo.log
log_level = info
